### ISSUE TITLE
Add a button on the botton right to allow to go up in the app

### ISSUE THREAD

**Issue by lionel-k** [burundiarxiv/burundiarxiv-web-client#7]
When an user is scrolling down, it becomes difficult to go up to the search bar. It could be user friendly to add the button on the bottom right for quick access to go up in the page. 

Ex: this [page](https://html-online.com/articles/dynamic-scroll-back-top-page-button-javascript/)

**Comment by muco-rolle** [comment]
Thanks indeed it was needed
